implemented typescript with appreducer (appreducer typescripted)
Team-Olya/frontend pull request #225
Opened 2023-07-01 18:07 UTC by halmber

2023-07-01 18:08 UTC, KOSMOSq commented
Тайп скрипт надо выучить, официальной документацией.
Её я дам!
Редакс надо переписать, своими домыслами.
Их я не дам!

2023-07-01 18:09 UTC, KOSMOSq commented
![image](https://github.com/Team-Olya/frontend/assets/79363503/73163168-bb72-40eb-b0cb-4008a0a2765d)

2023-07-02 09:53 UTC, monrit requested changes
1) там по ідеї буде конфлікт коли напишеш npm i, бо крейт реакт апп хоче тс нижче 5 версії.
2) не треба писати при імпорті редюсера .ts, воно і без того має тягнути, якщо не тягне то це баг і тре перезапустити ідєшку, або ж щось не так в тсконфігу

2023-07-02 10:30 UTC, halmber commented
> 1. там по ідеї буде конфлікт коли напишеш npm i, бо крейт реакт апп хоче тс нижче 5 версії.
> 2. не треба писати при імпорті редюсера .ts, воно і без того має тягнути, якщо не тягне то це баг і тре перезапустити ідєшку, або ж щось не так в тсконфігу

пофіксив

2023-07-02 10:35 UTC, monrit approved these changes
Фегня

2023-07-02 10:35 UTC, merged